name: Deploy to EC2
on: 
    push:
        branches: [master]

jobs: 
    builds: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2

            - name: Execute remote SSH commands using private key
              uses: appleboy/ssh-action@v1
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.PRIVATE_SSH_KEY }}
                port: 22
                script: |
                    cd Bridge-kun/
                    git pull origin master
                    export NVM_DIR="$HOME/.nvm"
                    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                    npm install
                    cd backend/
                    pm2 start "npm run dev" --name Indexer